import type { ContestantSlotConfig, GameSetupConfig } from "./game-types";

export const APP_TITLE = "LLM Jeopardy";
export const OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1";
export const SETUP_STORAGE_KEY = "llm-jeopardy.setup.v1";

export const DEFAULT_CONTESTANT_SLOTS: ContestantSlotConfig[] = [
  { id: "slot-1", label: "Contestant 1", modelId: "" },
  { id: "slot-2", label: "Contestant 2", modelId: "" },
  { id: "slot-3", label: "Contestant 3", modelId: "" },
  { id: "slot-4", label: "Contestant 4", modelId: "" },
];

export const DEFAULT_SETUP_CONFIG: GameSetupConfig = {
  boardMode: "autogenerated",
  hardcodedBoardId: "show-9527",
  gateway: {
    baseUrl: OPENROUTER_BASE_URL,
    apiKey: "",
  },
  contestants: DEFAULT_CONTESTANT_SLOTS,
};

export function loadSavedSetup(): GameSetupConfig {
  if (typeof window === "undefined") {
    return DEFAULT_SETUP_CONFIG;
  }

  try {
    const raw = window.localStorage.getItem(SETUP_STORAGE_KEY);
    if (!raw) {
      return DEFAULT_SETUP_CONFIG;
    }

    const parsed = JSON.parse(raw) as Partial<GameSetupConfig>;

    return {
      boardMode:
        parsed.boardMode === "hardcoded" ? "hardcoded" : "autogenerated",
      hardcodedBoardId:
        typeof parsed.hardcodedBoardId === "string" &&
        parsed.hardcodedBoardId.trim()
          ? parsed.hardcodedBoardId
          : DEFAULT_SETUP_CONFIG.hardcodedBoardId,
      gateway: {
        baseUrl:
          typeof parsed.gateway?.baseUrl === "string" &&
          parsed.gateway.baseUrl.trim()
            ? parsed.gateway.baseUrl
            : DEFAULT_SETUP_CONFIG.gateway.baseUrl,
        apiKey:
          typeof parsed.gateway?.apiKey === "string" ? parsed.gateway.apiKey : "",
      },
      contestants: mergeContestantSlots(parsed.contestants),
    };
  } catch {
    return DEFAULT_SETUP_CONFIG;
  }
}

export function saveSetup(setup: GameSetupConfig) {
  if (typeof window === "undefined") {
    return;
  }

  window.localStorage.setItem(SETUP_STORAGE_KEY, JSON.stringify(setup));
}

function mergeContestantSlots(
  storedSlots: Partial<ContestantSlotConfig>[] | undefined,
): ContestantSlotConfig[] {
  return DEFAULT_CONTESTANT_SLOTS.map((fallback, index) => {
    const stored = storedSlots?.[index];

    return {
      id: fallback.id,
      label:
        typeof stored?.label === "string" && stored.label.trim()
          ? stored.label
          : fallback.label,
      modelId: typeof stored?.modelId === "string" ? stored.modelId : "",
    };
  });
}
