export type BoardMode = "autogenerated" | "hardcoded";
export type AnswerKind = "who" | "what";
export type StreamChannel = "reasoning_content" | "reasoning_summary" | "content";

export interface ClueCard {
  id: string; category: string; value: number; clue: string;
  answer: string; canonicalResponse: string; answerKind: AnswerKind;
  sourceTitle: string; sourceUrl: string; description?: string;
}

export interface BoardCategory {
  id: string; title: string; clues: ClueCard[];
}

export interface ContestantDefinition {
  id: string; label: string; model: string;
}

export interface ContestantSlotConfig {
  id: string;
  label: string;
  modelId: string;
}

export interface GatewayConfig {
  baseUrl: string;
  apiKey: string;
}

export interface GameSetupConfig {
  boardMode: BoardMode;
  hardcodedBoardId: string;
  gateway: GatewayConfig;
  contestants: ContestantSlotConfig[];
}

export interface ModelOption {
  id: string;
  name: string;
  contextLength?: number | null;
  description?: string | null;
  promptPrice?: number | null;
  completionPrice?: number | null;
  requestPrice?: number | null;
  internalReasoningPrice?: number | null;
  sortPrice?: number | null;
}

export interface BoardPreset {
  id: string;
  title: string;
  description: string;
  board: BoardCategory[];
}

export interface AttemptResult {
  contestantId: string; attempt: number; decision: "buzz" | "pass" | "none";
  status: "completed" | "aborted" | "failed"; buzzMs: number | null;
  rawResponse: string; answerLine: string | null; normalizedAnswer: string | null;
  thoughtAboutCorrectAnswer: boolean; error?: string;
}

export type RoundStreamEvent =
  | { type: "round_started"; clue: ClueCard; contestantIds: string[]; }
  | { type: "attempt_started"; attempt: number; contestantIds: string[]; pastWrongAnswers: string[]; }
  | { type: "rebound_tick"; secondsLeft: number; }
  | { type: "contestant_started"; attempt: number; contestantId: string; }
  | { type: "contestant_delta"; attempt: number; contestantId: string; channel: StreamChannel; delta: string; }
  | { type: "buzz_locked"; attempt: number; contestantId: string; buzzMs: number; }
  | { type: "contestant_complete"; result: AttemptResult; }
  | { type: "judged"; attempt: number; contestantId: string; correct: boolean; canonicalResponse: string; pointsDelta: number; normalizedExpected: string; normalizedActual: string | null; }
  | { type: "round_finished"; outcome: "correct" | "skipped"; winnerId: string | null; canonicalResponse: string; reason: string; }
  | { type: "error"; message: string; };
