import wikipediaCache from "../data/wikipedia-random-cache.json";
import type { AnswerKind, BoardCategory } from "./game-types";
import {
  escapeRegExp,
  normalizeTriviaResponse,
  slugify,
  stripParenthetical,
  toCanonicalResponse,
} from "./format";

const CATEGORY_VALUES = [200, 400, 600, 800, 1000];
const LIVE_CATEGORY_COUNT = 6;
const LIVE_CLUES_PER_CATEGORY = 5;
const MAX_BUCKET_SIZE = 8;
const CATEGORY_ORDER = ["People", "Places", "Arts & Culture", "Science & Nature", "History & Society", "Sports"];

export interface WikipediaSummary {
  title: string;
  extract: string;
  description?: string;
  type?: string;
  content_urls?: { desktop?: { page?: string; }; };
  thumbnail?: unknown;
}

interface WikipediaCachePayload {
  pages?: WikipediaSummary[];
}

interface BuiltClue {
  category: string;
  clue: string;
  answerKind: AnswerKind;
  answer: string;
  sourceTitle: string;
  sourceUrl: string;
}

interface SubjectProfile {
  category: string;
  answerKind: AnswerKind;
  placeholder: string;
}

const WIKIPEDIA_PAGES = getWikipediaPages(wikipediaCache);

export function getAutogeneratedBoard(): BoardCategory[] {
  const scoredPages = WIKIPEDIA_PAGES.map((page): WikipediaSummary & {
    _score: number;
  } => ({
    ...page,
    _score: getNotabilityScore(page),
  }));

  scoredPages.sort((left, right) => right._score - left._score);
  return buildBoardFromSummaries(scoredPages);
}

function getNotabilityScore(summary: WikipediaSummary): number {
  let score = 0;
  const desc = (summary.description || "").toLowerCase();
  const extract = summary.extract.toLowerCase();

  // Visuals are a massive indicator of Wikipedia notability
  if (summary.thumbnail) score += 30;

  // Length indicates depth of topic
  if (summary.extract.length > 150) score += 10;
  if (summary.extract.length > 300) score += 15;

  // Short, punchy titles usually mean fundamental concepts
  const wordCount = summary.title.split(' ').length;
  if (wordCount <= 2) score += 10;

  // Specific fame markers
  if (/\b(academy award|nobel prize|grammy|emmy|pulitzer|bestselling|blockbuster|world war|president of the united states|prime minister|hall of fame)\b/.test(extract)) {
    score += 50;
  }

  // Slight bias toward major cultural exporters helps filter out extremely obscure localities
  if (/\b(american|british|french|german|japanese|chinese|russian)\b/.test(desc)) {
    score += 5;
  }

  // Hard penalties for the bottomless pit of Wikipedia stubs
  if (/\b(member of the|house of delegates|state senate|mayor of|minor league|junior|semi-professional|amateur|bishop of|archdiocese of|unincorporated community|census-designated place|moth|beetle|snail|fly|spider|wasp)\b/.test(extract)) {
    score -= 100;
  }

  return score + (Math.random() * 15); // Jitter to keep board fresh on reloads
}

function buildBoardFromSummaries(summaries: WikipediaSummary[]): BoardCategory[] {
  const buckets = new Map<string, BuiltClue[]>();
  for (const summary of summaries) {
    const clue = summarizeToClue(summary);
    if (clue) {
      const existing = buckets.get(clue.category) ?? [];
      if (
        !existing.some(
          (entry) =>
            normalizeTriviaResponse(entry.answer) ===
            normalizeTriviaResponse(clue.answer),
        )
      ) {
        buckets.set(clue.category, [...existing, clue].slice(0, MAX_BUCKET_SIZE));
      }
    }
  }

  const viableCategories = CATEGORY_ORDER.filter(cat => (buckets.get(cat)?.length ?? 0) >= LIVE_CLUES_PER_CATEGORY);

  return viableCategories.slice(0, LIVE_CATEGORY_COUNT).map(category => {
    const clues = (buckets.get(category) ?? [])
      .slice(0, LIVE_CLUES_PER_CATEGORY)
      .map((entry, index) => ({
        id: `${slugify(category)}-${slugify(entry.answer)}`,
        category, value: CATEGORY_VALUES[index] ?? 1000, clue: entry.clue, answer: entry.answer,
        canonicalResponse: toCanonicalResponse(entry.answerKind, entry.answer),
        answerKind: entry.answerKind, sourceTitle: entry.sourceTitle, sourceUrl: entry.sourceUrl
      }));
    return { id: slugify(category), title: category, clues };
  });
}

function summarizeToClue(summary: WikipediaSummary): BuiltClue | null {
  if (!summary.title || !summary.extract || !summary.content_urls?.desktop?.page || summary.type === "disambiguation") return null;
  const normTitle = stripParenthetical(summary.title);

  if (normTitle.length < 3 || normTitle.length > 36 || normTitle.includes(":") || /\d/.test(normTitle) || /^list of\b/i.test(normTitle)) return null;

  const profile = inferSubjectProfile(summary);
  if (!profile) return null;

  let clueText = summary.extract.replace(/\s+/g, " ").trim();
  let substitutionWorked = false;

  // 1. Try to replace the title if it appears at the very beginning
  const leadingRegex = new RegExp(`^(?:The\\s+|A\\s+|An\\s+)?${escapeRegExp(normTitle)}\\b`, "i");
  if (leadingRegex.test(clueText)) {
    clueText = clueText.replace(leadingRegex, profile.placeholder);
    substitutionWorked = true;
  }

  // 2. Try to replace any other explicit mentions of the title (or pre-comma short title)
  const shortTitle = normTitle.split(',')[0].trim();
  const answerRegex = new RegExp(`\\b${escapeRegExp(shortTitle)}\\b`, "gi");
  if (answerRegex.test(clueText)) {
    clueText = clueText.replace(answerRegex, profile.placeholder);
    substitutionWorked = true;
  }

  // If the article text didn't explicitly name the subject, we reject it.
  if (!substitutionWorked) return null;

  if (clueText.length < 55 || normalizeTriviaResponse(clueText).includes(normalizeTriviaResponse(normTitle))) return null;

  return { category: profile.category, clue: clueText, answerKind: profile.answerKind, answer: normTitle, sourceTitle: summary.title, sourceUrl: summary.content_urls.desktop.page };
}

function inferSubjectProfile(summary: WikipediaSummary): SubjectProfile | null {
  // Use the description if it exists, otherwise fall back to the pre-extracted sentence
  const desc = (summary.description || summary.extract).toLowerCase();

  if (/\b(singer|actor|actress|politician|player|writer|author|scientist|director|artist|musician|composer|footballer|coach|athlete|wrestler|racer|philosopher|general|commander|poet|novelist)\b/.test(desc)) return { category: "People", answerKind: "who", placeholder: "This person" };

  if (/\b(city|country|island|river|state|mountain|lake|town|county|region|village|province)\b/.test(desc)) return { category: "Places", answerKind: "what", placeholder: "This place" };

  if (/\b(species|planet|chemical|disease|animal|plant|biology|physics|chemistry|element|compound|galaxy)\b/.test(desc)) return { category: "Science & Nature", answerKind: "what", placeholder: "This entity" };

  if (/\b(film|album|novel|game|song|band|television|book|painting|sculpture|movie|franchise|series)\b/.test(desc)) return { category: "Arts & Culture", answerKind: "what", placeholder: "This work" };

  if (/\b(war|battle|empire|dynasty|treaty|history|revolution|company|organization|century|scandal)\b/.test(desc)) return { category: "History & Society", answerKind: "what", placeholder: "This subject" };

  if (/\b(baseball|football club|basketball|hockey|soccer club|sports league|tennis|golf|rugby|olympic|tournament|championship|stadium|arena)\b/.test(desc)) return { category: "Sports", answerKind: "what", placeholder: "This team or event" };

  return null;
}

function getWikipediaPages(cache: unknown): WikipediaSummary[] {
  if (Array.isArray(cache)) {
    return cache.filter(isWikipediaSummary);
  }

  if (cache && typeof cache === "object") {
    const payload = cache as WikipediaCachePayload;
    if (Array.isArray(payload.pages)) {
      return payload.pages.filter(isWikipediaSummary);
    }
  }

  return [];
}

function isWikipediaSummary(value: unknown): value is WikipediaSummary {
  if (!value || typeof value !== "object") {
    return false;
  }

  const candidate = value as Record<string, unknown>;
  return (
    typeof candidate.title === "string" &&
    typeof candidate.extract === "string"
  );
}
