import {
  startTransition,
  useDeferredValue,
  useEffect,
  useReducer,
  useRef,
  useState,
} from "react";
import {
  APP_TITLE,
  OPENROUTER_BASE_URL,
  loadSavedSetup,
  saveSetup,
} from "./lib/app-config";
import { HARD_CODED_BOARDS, getHardcodedBoard } from "./lib/boards";
import { buildContestants } from "./lib/contestants";
import {
  beginOpenRouterOAuth,
  clearOAuthCodeFromUrl,
  exchangeOpenRouterCodeForKey,
  fetchGatewayModels,
  getChatCompletionsUrl,
  getModelsUrl,
  isOpenRouterBaseUrl,
  normalizeGatewayBaseUrl,
} from "./lib/gateway";
import { runJeopardyRound } from "./lib/round-engine";
import { getAutogeneratedBoard } from "./lib/wikipedia";
import type {
  BoardCategory,
  ClueCard,
  ContestantDefinition,
  GameSetupConfig,
  ModelOption,
  RoundStreamEvent,
} from "./lib/game-types";

type ContestantRoundState = ContestantDefinition & {
  points: number;
  status: string;
  reasoning: string;
  content: string;
  wins: number;
  misses: number;
  buzzCount: number;
  totalBuzzMs: number;
  thoughtAboutCorrectAnswer: boolean;
};

type GameState = {
  board: BoardCategory[];
  contestants: ContestantRoundState[];
  activeContestantIds: string[];
  activeClue: ClueCard | null;
  playedClueIds: Set<string>;
  isRunning: boolean;
  winnerId: string | null;
  canonicalAnswer: string | null;
  reboundSeconds: number | null;
};

type Action =
  | {
      type: "INIT";
      board: BoardCategory[];
      contestants: ContestantDefinition[];
    }
  | { type: "START_CLUE"; clue: ClueCard }
  | { type: "CLEAR_CLUE" }
  | { type: "EVENT"; payload: RoundStreamEvent };

type ModelCatalogStatus = "idle" | "loading" | "ready" | "error";

const EMPTY_GAME_STATE: GameState = {
  board: [],
  contestants: [],
  activeClue: null,
  playedClueIds: new Set(),
  activeContestantIds: [],
  isRunning: false,
  winnerId: null,
  canonicalAnswer: null,
  reboundSeconds: null,
};

function gameReducer(state: GameState, action: Action): GameState {
  switch (action.type) {
    case "INIT":
      return {
        board: action.board,
        activeClue: null,
        playedClueIds: new Set(),
        activeContestantIds: action.contestants.map(
          (contestant) => contestant.id,
        ),
        isRunning: false,
        winnerId: null,
        canonicalAnswer: null,
        reboundSeconds: null,
        contestants: action.contestants.map((contestant) => ({
          ...contestant,
          points: 0,
          status: "idle",
          reasoning: "",
          content: "",
          wins: 0,
          misses: 0,
          buzzCount: 0,
          totalBuzzMs: 0,
          thoughtAboutCorrectAnswer: false,
        })),
      };
    case "START_CLUE":
      return {
        ...state,
        activeClue: action.clue,
        isRunning: true,
        winnerId: null,
        canonicalAnswer: null,
        reboundSeconds: null,
        activeContestantIds: state.contestants.map(
          (contestant) => contestant.id,
        ),
        contestants: state.contestants.map((contestant) => ({
          ...contestant,
          status: "thinking",
          reasoning: "",
          content: "",
          thoughtAboutCorrectAnswer: false,
        })),
      };
    case "CLEAR_CLUE":
      return {
        ...state,
        activeClue: null,
        isRunning: false,
        canonicalAnswer: null,
        winnerId: null,
        reboundSeconds: null,
        activeContestantIds: state.contestants.map(
          (contestant) => contestant.id,
        ),
        contestants: state.contestants.map((contestant) => ({
          ...contestant,
          status: "idle",
          reasoning: "",
          content: "",
          thoughtAboutCorrectAnswer: false,
        })),
      };
    case "EVENT": {
      const event = action.payload;

      if (event.type === "attempt_started") {
        return {
          ...state,
          reboundSeconds: null,
          activeContestantIds: event.contestantIds,
          contestants: state.contestants.map((contestant) =>
            event.contestantIds.includes(contestant.id)
              ? {
                  ...contestant,
                  status: "thinking",
                  reasoning: "",
                  content: "",
                  thoughtAboutCorrectAnswer: false,
                }
              : contestant,
          ),
        };
      }

      if (event.type === "rebound_tick") {
        return {
          ...state,
          reboundSeconds: event.secondsLeft > 0 ? event.secondsLeft : null,
        };
      }

      if (event.type === "contestant_delta") {
        return {
          ...state,
          contestants: state.contestants.map((contestant) =>
            contestant.id === event.contestantId
              ? {
                  ...contestant,
                  reasoning: event.channel.includes("reasoning")
                    ? contestant.reasoning + event.delta
                    : contestant.reasoning,
                  content:
                    event.channel === "content"
                      ? contestant.content + event.delta
                      : contestant.content,
                }
              : contestant,
          ),
        };
      }

      if (event.type === "buzz_locked") {
        return {
          ...state,
          contestants: state.contestants.map((contestant) =>
            contestant.id === event.contestantId
              ? {
                  ...contestant,
                  status: "buzzed",
                  buzzCount: contestant.buzzCount + 1,
                  totalBuzzMs: contestant.totalBuzzMs + event.buzzMs,
                }
              : { ...contestant, status: "idle" },
          ),
        };
      }

      if (event.type === "judged") {
        return {
          ...state,
          contestants: state.contestants.map((contestant) =>
            contestant.id === event.contestantId
              ? {
                  ...contestant,
                  status: event.correct ? "correct" : "wrong",
                  points: contestant.points + event.pointsDelta,
                  wins: event.correct ? contestant.wins + 1 : contestant.wins,
                  misses: !event.correct
                    ? contestant.misses + 1
                    : contestant.misses,
                }
              : contestant,
          ),
        };
      }

      if (event.type === "contestant_complete") {
        return {
          ...state,
          contestants: state.contestants.map((contestant) =>
            contestant.id === event.result.contestantId
              ? {
                  ...contestant,
                  status:
                    event.result.status === "failed"
                      ? "failed"
                      : contestant.status === "thinking"
                        ? event.result.decision === "pass"
                          ? "passed"
                          : "idle"
                        : contestant.status,
                  thoughtAboutCorrectAnswer:
                    event.result.thoughtAboutCorrectAnswer,
                }
              : contestant,
          ),
        };
      }

      if (event.type === "round_finished") {
        const nextPlayedClueIds = new Set(state.playedClueIds);
        if (state.activeClue) {
          nextPlayedClueIds.add(state.activeClue.id);
        }

        return {
          ...state,
          isRunning: false,
          playedClueIds: nextPlayedClueIds,
          reboundSeconds: null,
          winnerId: event.outcome === "correct" ? event.winnerId : null,
          canonicalAnswer: event.canonicalResponse,
        };
      }

      return state;
    }
    default:
      return state;
  }
}

export default function App() {
  const [setup, setSetup] = useState<GameSetupConfig>(() => loadSavedSetup());
  const [gameState, dispatch] = useReducer(gameReducer, EMPTY_GAME_STATE);
  const [isSetupOpen, setIsSetupOpen] = useState(true);
  const [modelCatalog, setModelCatalog] = useState<ModelOption[]>([]);
  const [modelCatalogStatus, setModelCatalogStatus] =
    useState<ModelCatalogStatus>("idle");
  const [modelCatalogError, setModelCatalogError] = useState<string | null>(
    null,
  );
  const [gatewayMessage, setGatewayMessage] = useState<string | null>(null);
  const [isOAuthBusy, setIsOAuthBusy] = useState(false);
  const [modelFilter, setModelFilter] = useState("");
  const deferredModelFilter = useDeferredValue(
    modelFilter.trim().toLowerCase(),
  );
  const tapeEndRefs = useRef<Record<string, HTMLDivElement | null>>({});

  useEffect(() => {
    saveSetup(setup);
  }, [setup]);

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const code = params.get("code");
    if (!code) {
      return;
    }

    let cancelled = false;

    const finishOAuth = async () => {
      setIsOAuthBusy(true);
      setGatewayMessage("Finishing OpenRouter sign-in...");
      setIsSetupOpen(true);

      try {
        const apiKey = await exchangeOpenRouterCodeForKey(code);
        if (cancelled) {
          return;
        }

        const nextGateway = {
          baseUrl: OPENROUTER_BASE_URL,
          apiKey,
        };

        setSetup((current) => ({
          ...current,
          gateway: nextGateway,
        }));
        setModelCatalogStatus("loading");
        setModelCatalogError(null);
        setGatewayMessage(
          `Loading models from ${getModelsUrl(nextGateway.baseUrl)}...`,
        );

        const models = await fetchGatewayModels(nextGateway);
        if (cancelled) {
          return;
        }

        startTransition(() => {
          setModelCatalog(models);
          setModelCatalogStatus("ready");
        });
        setGatewayMessage(`OpenRouter key connected. Loaded ${models.length} models.`);
      } catch (error) {
        if (cancelled) {
          return;
        }

        setGatewayMessage(getErrorMessage(error));
      } finally {
        clearOAuthCodeFromUrl();
        if (!cancelled) {
          setIsOAuthBusy(false);
        }
      }
    };

    void finishOAuth();

    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    Object.values(tapeEndRefs.current).forEach((element) =>
      element?.scrollIntoView({ behavior: "auto" }),
    );
  }, [gameState.contestants]);

  const normalizedBaseUrl = normalizeGatewayBaseUrl(setup.gateway.baseUrl);
  const openRouterSelected = isOpenRouterBaseUrl(setup.gateway.baseUrl);
  const currentBoardPreset =
    HARD_CODED_BOARDS.find((preset) => preset.id === setup.hardcodedBoardId) ??
    HARD_CODED_BOARDS[0];
  const inferredContestants = buildContestants(setup.contestants, modelCatalog);
  const canLaunchGame =
    Boolean(normalizedBaseUrl) &&
    Boolean(setup.gateway.apiKey.trim()) &&
    inferredContestants.length >= 2;

  const filteredModels = deferredModelFilter
    ? modelCatalog.filter((model) => {
        const haystack = `${model.name} ${model.id}`.toLowerCase();
        return haystack.includes(deferredModelFilter);
      })
    : modelCatalog;

  const visibleContestants = gameState.activeClue
    ? gameState.contestants.filter((contestant) =>
        gameState.activeContestantIds.includes(contestant.id),
      )
    : gameState.contestants;

  const canDismissClue = !gameState.isRunning && gameState.activeClue !== null;
  const overthinkers = gameState.contestants
    .filter(
      (contestant) =>
        contestant.thoughtAboutCorrectAnswer &&
        contestant.status !== "correct" &&
        gameState.activeContestantIds.includes(contestant.id),
    )
    .map((contestant) => contestant.label);

  function updateSetup(mutator: (current: GameSetupConfig) => GameSetupConfig) {
    setSetup((current) => mutator(current));
  }

  async function refreshModels(
    gatewayOverride?: GameSetupConfig["gateway"],
  ): Promise<void> {
    const nextGateway = gatewayOverride ?? setup.gateway;
    const nextBaseUrl = normalizeGatewayBaseUrl(nextGateway.baseUrl);

    if (!nextBaseUrl) {
      setModelCatalogStatus("error");
      setModelCatalogError("Enter a valid gateway base URL first.");
      return;
    }

    const normalizedGateway = {
      ...nextGateway,
      baseUrl: nextBaseUrl,
    };

    updateSetup((current) => ({
      ...current,
      gateway: {
        ...current.gateway,
        baseUrl: nextBaseUrl,
      },
    }));

    setModelCatalogStatus("loading");
    setModelCatalogError(null);
    setGatewayMessage(`Loading models from ${getModelsUrl(nextBaseUrl)}...`);

    try {
      const models = await fetchGatewayModels(normalizedGateway);
      startTransition(() => {
        setModelCatalog(models);
        setModelCatalogStatus("ready");
      });
      setGatewayMessage(`Loaded ${models.length} models.`);
    } catch (error) {
      setModelCatalogStatus("error");
      setModelCatalogError(getErrorMessage(error));
      setGatewayMessage(null);
    }
  }

  async function handleOpenRouterConnect() {
    updateSetup((current) => ({
      ...current,
      gateway: {
        ...current.gateway,
        baseUrl: OPENROUTER_BASE_URL,
      },
    }));
    setGatewayMessage("Redirecting to OpenRouter...");

    try {
      await beginOpenRouterOAuth();
    } catch (error) {
      setGatewayMessage(getErrorMessage(error));
    }
  }

  function launchGame() {
    const nextBaseUrl = normalizeGatewayBaseUrl(setup.gateway.baseUrl);
    const nextSetup = {
      ...setup,
      gateway: {
        ...setup.gateway,
        baseUrl: nextBaseUrl,
      },
    };

    const contestants = buildContestants(nextSetup.contestants, modelCatalog);
    const board =
      nextSetup.boardMode === "hardcoded"
        ? getHardcodedBoard(nextSetup.hardcodedBoardId)
        : getAutogeneratedBoard();

    setSetup(nextSetup);
    dispatch({
      type: "INIT",
      board,
      contestants,
    });
    setIsSetupOpen(false);
  }

  function playClue(clue: ClueCard) {
    if (gameState.isRunning || !gameState.contestants.length) {
      return;
    }

    dispatch({ type: "START_CLUE", clue });
    void runJeopardyRound({
      clue,
      contestants: gameState.contestants.map(toContestantDefinition),
      gateway: {
        baseUrl: normalizeGatewayBaseUrl(setup.gateway.baseUrl),
        apiKey: setup.gateway.apiKey.trim(),
      },
      writeEvent: (event) => dispatch({ type: "EVENT", payload: event }),
    }).catch((error) => {
      console.warn("Round failed:", error);
      dispatch({ type: "CLEAR_CLUE" });
      setGatewayMessage(getErrorMessage(error));
      setIsSetupOpen(true);
    });
  }

  return (
    <>
      <header className="app-toolbar">
        <div className="toolbar-copy">
          <h1>{APP_TITLE}</h1>
        </div>

        <div className="toolbar-actions">
          {!isSetupOpen && (
            <button
              type="button"
              className="toolbar-button"
              onClick={() => setIsSetupOpen(true)}
            >
              Reconfigure
            </button>
          )}

          <button
            type="button"
            className="toolbar-button primary"
            disabled={isSetupOpen && !canLaunchGame}
            onClick={() => {
              if (isSetupOpen) {
                if (canLaunchGame) {
                  launchGame();
                }
                return;
              }

              setIsSetupOpen(true);
            }}
          >
            {isSetupOpen ? "Launch Game" : "New Setup"}
          </button>
        </div>
      </header>

      {isSetupOpen ? (
        <main className="setup-screen">
          <section className="setup-grid">
            <article className="setup-card">
              <div className="card-header">
                <p className="card-step">Step 1</p>
                <h3>Board Source</h3>
              </div>

              <div className="choice-row">
                <label className="choice-card">
                  <input
                    type="radio"
                    name="board-mode"
                    checked={setup.boardMode === "autogenerated"}
                    onChange={() =>
                      updateSetup((current) => ({
                        ...current,
                        boardMode: "autogenerated",
                      }))
                    }
                  />
                  <span>Autogenerated board</span>
                  <small>
                    Build a fresh board from the bundled Wikipedia cache import.
                  </small>
                </label>

                <label className="choice-card">
                  <input
                    type="radio"
                    name="board-mode"
                    checked={setup.boardMode === "hardcoded"}
                    onChange={() =>
                      updateSetup((current) => ({
                        ...current,
                        boardMode: "hardcoded",
                      }))
                    }
                  />
                  <span>Hardcoded board</span>
                  <small>
                    Placeholder curated boards for now; replace them later.
                  </small>
                </label>
              </div>

              {setup.boardMode === "hardcoded" && (
                <label className="field">
                  <span>Curated board preset</span>
                  <select
                    value={setup.hardcodedBoardId}
                    onChange={(event) =>
                      updateSetup((current) => ({
                        ...current,
                        hardcodedBoardId: event.target.value,
                      }))
                    }
                  >
                    {HARD_CODED_BOARDS.map((preset) => (
                      <option key={preset.id} value={preset.id}>
                        {preset.title}
                      </option>
                    ))}
                  </select>
                  <small>{currentBoardPreset.description}</small>
                </label>
              )}
            </article>

            <article className="setup-card">
              <div className="card-header">
                <p className="card-step">Step 2</p>
                <h3>AI Gateway</h3>
              </div>

              <label className="field">
                <span>Gateway base URL</span>
                <input
                  type="url"
                  value={setup.gateway.baseUrl}
                  placeholder={OPENROUTER_BASE_URL}
                  onChange={(event) =>
                    updateSetup((current) => ({
                      ...current,
                      gateway: {
                        ...current.gateway,
                        baseUrl: event.target.value,
                      },
                    }))
                  }
                />
                <small>
                  This app always calls <code>/chat/completions</code> and{" "}
                  <code>/models</code> under the base URL you enter here.
                </small>
              </label>

              <label className="field">
                <span>API key</span>
                <div className="field-with-overlay">
                  <input
                    type="password"
                    value={setup.gateway.apiKey}
                    placeholder="Paste a key or connect OpenRouter"
                    onChange={(event) =>
                      updateSetup((current) => ({
                        ...current,
                        gateway: {
                          ...current.gateway,
                          apiKey: event.target.value,
                        },
                      }))
                    }
                  />

                  {openRouterSelected && !setup.gateway.apiKey.trim() && (
                    <button
                      type="button"
                      className="inline-connect-button"
                      disabled={isOAuthBusy}
                      onClick={() => void handleOpenRouterConnect()}
                    >
                      {isOAuthBusy ? "Connecting..." : "Connect OpenRouter"}
                    </button>
                  )}
                </div>
              </label>

              <div className="endpoint-preview">
                <div>
                  <span>Models</span>
                  <code>
                    {normalizedBaseUrl
                      ? getModelsUrl(normalizedBaseUrl)
                      : "Enter a base URL"}
                  </code>
                </div>
                <div>
                  <span>Inference</span>
                  <code>
                    {normalizedBaseUrl
                      ? getChatCompletionsUrl(normalizedBaseUrl)
                      : "Enter a base URL"}
                  </code>
                </div>
              </div>

              {gatewayMessage && (
                <p className="helper-message">{gatewayMessage}</p>
              )}
              {modelCatalogError && (
                <p className="helper-message error">{modelCatalogError}</p>
              )}
            </article>

            <article className="setup-card setup-card-wide">
              <div className="card-header card-header-actions">
                <div className="card-header-main">
                  <p className="card-step">Step 3</p>
                  <h3>Contestant Models</h3>
                </div>

                <button
                  type="button"
                  className="panel-button model-load-button"
                  disabled={modelCatalogStatus === "loading"}
                  onClick={() => void refreshModels()}
                >
                  {modelCatalogStatus === "loading"
                    ? "Loading models..."
                    : "Load /models"}
                </button>
              </div>

              {modelCatalogStatus === "ready" && modelCatalog.length > 0 ? (
                <div className="models-toolbar">
                  <label className="field field-compact model-search-field">
                    <span>Search models</span>
                    <input
                      type="search"
                      value={modelFilter}
                      placeholder="Filter by model name or id"
                      onChange={(event) => setModelFilter(event.target.value)}
                    />
                  </label>

                  <p className="helper-message model-toolbar-copy">
                    {openRouterSelected
                      ? `Showing ${filteredModels.length} of ${modelCatalog.length} models, sorted from cheapest to most expensive.`
                      : `Showing ${filteredModels.length} of ${modelCatalog.length} models.`}
                  </p>
                </div>
              ) : (
                <p className="helper-message model-toolbar-copy">
                  Load the gateway catalog after configuring your base URL and
                  key, then pick models for each contestant.
                </p>
              )}

              <div className="contestant-grid">
                {setup.contestants.map((slot) => {
                  const modelOptions = getOptionsForSlot(
                    slot.modelId,
                    filteredModels,
                    modelCatalog,
                    Boolean(deferredModelFilter),
                  );

                  return (
                    <div key={slot.id} className="contestant-card">
                      <label className="field">
                        <span>Label</span>
                        <input
                          type="text"
                          value={slot.label}
                          onChange={(event) =>
                            updateSetup((current) => ({
                              ...current,
                              contestants: current.contestants.map(
                                (candidate) =>
                                  candidate.id === slot.id
                                    ? {
                                        ...candidate,
                                        label: event.target.value,
                                      }
                                    : candidate,
                              ),
                            }))
                          }
                        />
                      </label>

                      <label className="field">
                        <span>Model</span>
                        <select
                          value={slot.modelId}
                          onChange={(event) =>
                            updateSetup((current) => ({
                              ...current,
                              contestants: current.contestants.map(
                                (candidate) =>
                                  candidate.id === slot.id
                                    ? {
                                        ...candidate,
                                        modelId: event.target.value,
                                      }
                                    : candidate,
                              ),
                            }))
                          }
                        >
                          <option value="">Choose a model</option>
                          {modelOptions.map((model) => (
                            <option key={model.id} value={model.id}>
                              {formatModelLabel(model)}
                            </option>
                          ))}
                        </select>
                      </label>
                    </div>
                  );
                })}
              </div>
            </article>
          </section>
        </main>
      ) : (
        <>
          <section className="stage">
            {!gameState.activeClue ? (
              <div className="board-view">
                {gameState.board.map((category) => (
                  <div key={category.id} className="board-col">
                    <div className="board-cat">{category.title}</div>
                    {category.clues.map((clue) => {
                      const played = gameState.playedClueIds.has(clue.id);

                      return (
                        <button
                          key={clue.id}
                          type="button"
                          className="board-tile"
                          disabled={played || gameState.isRunning}
                          onClick={() => playClue(clue)}
                          title={`${clue.clue} is ${clue.answer}`}
                        >
                          ${clue.value}
                        </button>
                      );
                    })}
                  </div>
                ))}
              </div>
            ) : (
              <div
                className={`clue-view ${canDismissClue ? "is-clickable" : ""}`}
                onClick={() =>
                  canDismissClue && dispatch({ type: "CLEAR_CLUE" })
                }
              >
                <div className="clue-text">{gameState.activeClue.clue}</div>

                {gameState.isRunning &&
                  !gameState.winnerId &&
                  gameState.reboundSeconds === null && (
                    <div
                      className="shot-clock"
                      key={gameState.activeContestantIds.join("-")}
                    >
                      <div className="shot-clock-fill" />
                    </div>
                  )}

                {gameState.reboundSeconds !== null &&
                  gameState.reboundSeconds > 0 && (
                    <div className="rebound-timer">
                      Rebounding in {gameState.reboundSeconds}...
                    </div>
                  )}

                {gameState.canonicalAnswer && (
                  <div className="clue-answer">
                    {!gameState.winnerId && (
                      <small>
                        {overthinkers.length > 0
                          ? `Stumped! (But ${overthinkers.join(" and ")} thought of it)`
                          : "Stumped! The correct response is:"}
                      </small>
                    )}
                    {gameState.canonicalAnswer}
                  </div>
                )}
              </div>
            )}
          </section>

          <section className="podiums-container">
            {visibleContestants.map((contestant) => {
              const isWinner = gameState.winnerId === contestant.id;
              const isFailed = contestant.status === "failed";
              const isWrong = contestant.status === "wrong";
              const isPassed = contestant.status === "passed";
              const hasReasoning = contestant.reasoning.length > 0;
              const hasContent = contestant.content.length > 0;
              const averageSpeed =
                contestant.buzzCount > 0
                  ? Math.round(contestant.totalBuzzMs / contestant.buzzCount)
                  : "--";

              return (
                <div
                  key={contestant.id}
                  className={`podium ${isWinner ? "winner" : ""} ${isWrong ? "wrong" : ""} ${isFailed ? "failed" : ""} ${isPassed ? "passed" : ""} ${contestant.status === "buzzed" ? "buzzed" : ""}`}
                >
                  <div className="podium-header">
                    <div className="podium-name">
                      {contestant.label}{" "}
                      {contestant.thoughtAboutCorrectAnswer &&
                        !isWinner &&
                        "💡"}
                    </div>
                    <div className="podium-score">${contestant.points}</div>
                  </div>

                  <div className="podium-body">
                    {!gameState.activeClue ? (
                      <div className="podium-stats">
                        <div className="stat-box">
                          <span className="stat-label">Wins</span>
                          <span className="stat-value">{contestant.wins}</span>
                        </div>
                        <div className="stat-box">
                          <span className="stat-label">Misses</span>
                          <span className="stat-value">
                            {contestant.misses}
                          </span>
                        </div>
                        <div className="stat-box">
                          <span className="stat-label">Avg Spd</span>
                          <span className="stat-value">
                            {averageSpeed === "--" ? "--" : `${averageSpeed}ms`}
                          </span>
                        </div>
                      </div>
                    ) : (
                      <>
                        {hasReasoning && (
                          <div
                            className="tape-section"
                            style={{ flex: hasContent ? 1 : 2 }}
                          >
                            <div className="tape-label">Thinking</div>
                            <div className="tape-content">
                              <div className="tape-inner">
                                {contestant.reasoning}
                                <div
                                  ref={(element) => {
                                    tapeEndRefs.current[`${contestant.id}-r`] =
                                      element;
                                  }}
                                />
                              </div>
                            </div>
                          </div>
                        )}

                        {hasContent && (
                          <div
                            className="tape-section"
                            style={{ flex: hasReasoning ? 1 : 2 }}
                          >
                            <div className="tape-label">Output</div>
                            <div className="tape-content">
                              <div className="tape-inner output">
                                {contestant.content}
                                <div
                                  ref={(element) => {
                                    tapeEndRefs.current[`${contestant.id}-c`] =
                                      element;
                                  }}
                                />
                              </div>
                            </div>
                          </div>
                        )}
                      </>
                    )}
                  </div>

                  {isWrong && <div className="status-overlay wrong">WRONG</div>}
                  {isFailed && (
                    <div className="status-overlay failed">API FAILED</div>
                  )}
                  {isPassed && (
                    <div className="status-overlay passed">PASSED</div>
                  )}
                  {isWinner && (
                    <div className="status-overlay winner">WINNER</div>
                  )}
                </div>
              );
            })}
          </section>
        </>
      )}
    </>
  );
}

function getOptionsForSlot(
  selectedModelId: string,
  filteredModels: ModelOption[],
  allModels: ModelOption[],
  filterActive: boolean,
): ModelOption[] {
  const options = filterActive ? filteredModels : allModels;
  if (!selectedModelId) {
    return options;
  }

  const selectedModel = allModels.find(
    (model) => model.id === selectedModelId,
  ) ?? {
    id: selectedModelId,
    name: `${selectedModelId} (saved selection)`,
    contextLength: null,
    description: null,
  };

  if (options.some((model) => model.id === selectedModel.id)) {
    return options;
  }

  return [selectedModel, ...options];
}

function formatModelLabel(model: ModelOption): string {
  const details: string[] = [];

  if (model.promptPrice !== null && model.promptPrice !== undefined) {
    details.push(`in ${formatPrice(model.promptPrice)}`);
  }

  if (model.completionPrice !== null && model.completionPrice !== undefined) {
    details.push(`out ${formatPrice(model.completionPrice)}`);
  }

  if (model.contextLength) {
    details.push(`${Intl.NumberFormat().format(model.contextLength)} ctx`);
  }

  return details.length > 0
    ? `${model.name} · ${details.join(" · ")}`
    : model.name;
}

function getErrorMessage(error: unknown): string {
  if (error instanceof Error && error.message) {
    return error.message;
  }

  return "Something went wrong.";
}

function toContestantDefinition(
  contestant: ContestantRoundState,
): ContestantDefinition {
  return {
    id: contestant.id,
    label: contestant.label,
    model: contestant.model,
  };
}

function formatPrice(value: number): string {
  const perMillion = value * 1_000_000;

  if (perMillion === 0) {
    return "$0/M";
  }

  if (perMillion >= 0.01) {
    return `$${perMillion.toFixed(2)}/M`;
  }

  return `$${perMillion.toPrecision(2)}/M`;
}
